SET PATH=F:\0_Tools\Keil_v5\ARM\ARMCC\Bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files\Broadcom\Broadcom 802.11 Network Adapter\Driver;;;;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
SET ARMCC5_ASMOPT=--diag_suppress=9931
SET ARMCC5_CCOPT=--diag_suppress=9931
SET ARMCC5_LINKOPT=--diag_suppress=9931
SET CPU_TYPE=TM4C123GH6PM
SET CPU_VENDOR=Texas Instruments
SET UV2_TARGET=Target 1
SET CPU_CLOCK=0x00F42400
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmAsm" --Via ".\generated_output\startup_new._ia"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "generated_listing\main._ip"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\generated_output\main.__i"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "generated_listing\adc_handler._ip"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\generated_output\adc_handler.__i"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "generated_listing\comparator_handler._ip"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\generated_output\comparator_handler.__i"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "generated_listing\cyclic_activity_handler._ip"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\generated_output\cyclic_activity_handler.__i"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "generated_listing\gpio_handler._ip"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\generated_output\gpio_handler.__i"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "generated_listing\interrupt_handler._ip"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\generated_output\interrupt_handler.__i"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "generated_listing\lcd_handler._ip"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\generated_output\lcd_handler.__i"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "generated_listing\motion_handler._ip"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\generated_output\motion_handler.__i"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "generated_listing\printing_handler._ip"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\generated_output\printing_handler.__i"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "generated_listing\pwm_handler._ip"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\generated_output\pwm_handler.__i"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "generated_listing\ssi_handler._ip"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\generated_output\ssi_handler.__i"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "generated_listing\system_handler._ip"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\generated_output\system_handler.__i"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "generated_listing\timer_handler._ip"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\generated_output\timer_handler.__i"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "generated_listing\i2c_handler._ip"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\generated_output\i2c_handler.__i"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "generated_listing\accelerometer_handler._ip"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\generated_output\accelerometer_handler.__i"
"F:\0_Tools\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "generated_listing\shift_register_handler._ip"
